name: antri_tino
description: Antri Kapan Saja dan Dimana Saja

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.5

  intl: ^0.16.1
  uuid: ^2.0.4

  progress_dialog: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic

  assets:
    - assets/images/
